name: 'Build'

on:
    push:
        branches:
            - test

jobs:
    build:
        name: 'Build'
        runs-on: 'ubuntu-20.04'
        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v2'
              with:
                  path: 'php-rdkafka-doc'
            - name: 'Build'
              uses: './php-rdkafka-doc/.github/actions/build'
